### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Avyansh0001** [punctuations/cmdf#12]
When I'm trying to use your service, it says 501 Internal Server Error. Is this error happening with all other domains as well?

Regards,
[Avyansh Ralph](https://avyanshralph.xyz)

**Comment by punctuations** [comment]
Hey! So sorry that this seems to be happening, I'm already working on fixing this, I've had to touch base with supabase support a lot quite recently, as it seems I have to migrate the database to a new one, as in the past the log has been maxing out and caused the database to crash; however, this time may be different, I'll keep this issue open and up-to-date with the status of things.

**Comment by punctuations** [comment]
The issue is fixed, the database will be migrated shortly to a more stable version to prevent this from happening in the future!
